version: '3.8'

services:
  postgresdb:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: airport
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   image: airport-backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend/src:/usr/src/app/src
  #   depends_on:
  #     - postgresdb
  #     # - mongodb

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   image: airport-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
